All features completed
roshanasingh4/trial_project pull request #1
Opened 2023-05-05 14:49 UTC by roshanasingh4

I have completed all the checkmarks related to this project including the special access instructions as well as the figma design to the pixel. I have implement the menu bar as well as the animation as it was instructed.

Thanks for taking the time to review it.

2023-05-05 14:57 UTC, roshanasingh4 commented
Hi @roshanasingh4,

Great job so far you have spent a good amount of time in this project.
There are still some issues that need to be taken care of.

![image](https://user-images.githubusercontent.com/88576930/236492382-42f9e7d7-2118-4799-a585-f6469aab1375.png)

## Highlights
- Good looking website ✔️ 
- Readme file professional ✔️

## Required Changes ♻️
-Check the comments under the review.

## Optional suggestions

Well, there is one issue which is not blocking anything but it would be good to have a alt info on all the img's as well as the relevant section, this will greatly and positively impact your credit score greatly.

2023-05-05 15:50 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @roshanasingh4 , 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub's review features! 🥇 

## Required Changes ♻️
_Check the comments under the review._

You did a good job working on your review! However, there's still room to improve, starting by don't being too general with your comments:

> You need to use more and more semantic HTML which will help you in the longer run. 

- [ ] This comment is too vague. Instead, consider using [inline comments](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) from the GitHub's review features to be specific about which sections of the HTML could use semantic tags, and also don't forget to be polite, sound like you're giving suggestions instead of orders and provide an explanation on why using semantic tags is better! 🤓 🔧 


> You also need to make sure that the footer colors have good contrast so that it is accessible to everyone

- [ ] Please also rephrase this comment to sound polite:

>This is a polite suggestion: "I think it would be better to use semantic tags"
>
>This reads as an order: "Use semantic tags"


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

- [ ] **[OPTIONAL]** It would be good if you use a couple of emojis in the review. They make the code review more human-friendly 👽 🤖 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 16:07 UTC, roshanasingh4 commented
Hi @roshanasingh4,

Great job so far you have spent a good amount of time in this project.
There are still some issues that need to be taken care of.

![image](https://user-images.githubusercontent.com/88576930/236492382-42f9e7d7-2118-4799-a585-f6469aab1375.png)

## Highlights
- Good looking website ✔️ 
- Readme file professional ✔️

## Required Changes ♻️
- Check the comments under the review

## Optional suggestions

Well, there is one issue which is not blocking anything but it would be good to have a alt info on all the img's as well as the relevant section, this will greatly and positively impact your credit score greatly.

2023-05-05 16:56 UTC, Shedrack-Sunday requested changes
Hello @roshanasingh4        👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well so far in the project,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- partial use of GitHub features for review ✔️   
  
# Required Changes  🌵 

- [ ] I noticed you've not use the inline comment to give a review to your code. Kindly use the steps below:
- Use the "Review changes" feature from GitHub [Vidoe lik](https://www.loom.com/share/e847c46aa4814534b23b3a8e4dd60d6d)
## Steps pictures:
![image](https://user-images.githubusercontent.com/50990925/236519627-5c6e8d2b-7d93-4f34-b6c7-1c028fe50079.png)

- Follow this link [Access](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) provided  my microverse, then make the inline review changes as suggested by the last reviewer  

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-06 04:53 UTC, roshanasingh4 reviewed
Hi @roshanasingh4,

Great job so far you have spent a good amount of time in this project.
There are still some issues that need to be taken care of.

![image](https://user-images.githubusercontent.com/88576930/236492382-42f9e7d7-2118-4799-a585-f6469aab1375.png)

## Highlights
- Good looking website ✔️ 
- Readme file professional ✔️

## Required Changes ♻️
- Check the comments under the review

## Optional suggestions

Well, there is one issue which is not blocking anything but it would be good to have a alt info on all the img's as well as the relevant section, this will greatly and positively impact your credit score greatly.

2023-05-06 04:53 UTC, roshanasingh4 commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
You can remove the unnecessary markup and make the readme file cleaner

2023-05-06 05:09 UTC, wayungi commented on public/index.html
> +    -->
- [ ] Comment is clear, and the reason for change requests is given. Comment given suggestively 👏🏾

2023-05-06 05:10 UTC, wayungi commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [ ] Great work !!!.. This is how it's done. Always keep it clear, and simple, explain why, and be polite.

2023-05-06 05:12 UTC, wayungi approved these changes
Hi @roshanasingh4 , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] Used Github inline comments 👍🏾 
- [ ] Comments are clear 👍🏾 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 05:35 UTC, merged